server.servlet.context-path=/api

# static resources location
spring.resources.static-locations=classpath:/META-INF/resources/,\
  classpath:/resources/,\
  classpath:/static/,\
  classpath:/public/,\
  classpath:/frontend/build/

# default page
spring.mvc.view.prefix=/static/
spring.mvc.view.suffix=.html